export const HTTP_STATUS = {
	CREATED: 201,
	OK: 200,
	NO_CONTENT: 204,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	CONFLICT: 409,
	TOO_MANY_REQUESTS: 429,
	INTERNAL_ERROR: 500,
	SERVICE_UNAVAILABLE: 503,
};

export const HTTP_MESSAGES = {
	USER_CREATED: 'User created',
	USER_UPDATED: 'User updated successfully',
	USER_DELETED: 'User deleted',
	USER_NOT_FOUND: 'User not found',
	STORY_CREATED: 'Story created successfully',
	STORY_UPDATED: 'Story updated successfully',
	STORY_DELETED: 'Story deleted successfully',
	STORY_NOT_FOUND: 'Story not found',
	RESOURCE_NOT_FOUND: 'Resource not found',
	INTERNAL_DATABASE_ERROR: 'Internal database error',
	ROUTE_NOT_FOUND: 'Route not found',
	VALIDATION_FAILED: 'Validation failed',
	UNAUTHORIZED: 'Unauthorized Access',
	FORBIDDEN: 'Forbidden',
	INTERNAL_ERROR: 'Internal error occurred',
	CONFLICT_ERROR: 'Conflict error occurred',
	USERNAME_ALREADY_EXISTS: 'Username already exists',
	EMAIL_ALREADY_EXISTS: 'Email already exists',
	INVALID_CREDENTIALS: 'Invalid email',
	INVALID_PASSWORD: 'Invalid password',
	INVALID_TOKEN: 'Invalid or expired token',
	EMAIL_CONFIRMATION_SENT:
		'Confirmation email sent successfully. Please check your email to verify your account.',
	EMAIL_ALREADY_CONFIRMED: 'Email is already confirmed',
	EMAIL_CONFIRMED_SUCCESSFULLY: 'Email confirmed successfully. You can now login.',
	EMAIL_CONFIRMATION_RESENT: 'Confirmation email resent successfully. Please check your email.',
	EMAIL_NOT_CONFIRMED: 'Please confirm your email before logging in',
	CATEGORY_CREATED: 'Category created successfully',
	CATEGORY_FETCHED: 'Category fetched successfully',
	CATEGORY_UPDATED: 'Category updated successfully',
	CATEGORY_DELETED: 'Category deleted successfully',
	CATEGORY_EXISTS: 'Category already exists',
	CATEGORY_NOT_FOUND: 'Category not found',
	INVALID_CATEGORIES: 'One or more categories do not exist',
	SEEDED_SUCCESSFULLY: 'Categories seeded successfully',
	PASSWORD_CHANGE_EMAIL_SENT: 'Password change confirmation code sent to your email',
	PASSWORD_CHANGE_CODE_INVALID: 'Invalid or expired password change code',
	PASSWORD_CHANGE_CODE_VERIFIED: 'Password change code verified successfully',
	PASSWORD_CHANGED_SUCCESSFULLY: 'Password changed successfully',
	CURRENT_PASSWORD_INCORRECT: 'Current password is incorrect',
};
