export const HTTP_STATUS = {
	CREATED: 201,
	OK: 200,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	INTERNAL_ERROR: 500,
};

export const HTTP_MESSAGES = {
	USER_CREATED: 'User created',
	USER_UPDATED: 'User updated successfully',
	USER_DELETED: 'User deleted',
	USER_NOT_FOUND: 'User not found',
	STORY_CREATED: 'Story created successfully',
	STORY_UPDATED: 'Story updated successfully',
	STORY_DELETED: 'Story deleted successfully',
	STORY_NOT_FOUND: 'Story not found',
	RESOURCE_NOT_FOUND: 'Resource not found',
	INTERNAL_DATABASE_ERROR: 'Internal database error',
	ROUTE_NOT_FOUND: 'Route not found',
	FAILED_CREATE_USER: 'Failed to create user',
	FAILED_GET_USERS: 'Failed to get users',
	FAILED_FETCH_USER: 'Failed to fetch user',
	FAILED_UPDATE_USER: 'Failed to update user',
	FAILED_DELETE_USER: 'Failed to delete user',
	FAILED_CREATE_STORY: 'Failed to create story',
	FAILED_GET_STORIES: 'Failed to get stories',
	FAILED_FETCH_STORY: 'Failed to fetch story',
	FAILED_UPDATE_STORY: 'Failed to update story',
	FAILED_DELETE_STORY: 'Failed to delete story',
	VALIDATION_FAILED: 'Validation failed',
	UNAUTHORIZED: 'Unauthorized Access',
	FORBIDDEN: 'Forbidden',
	INTERNAL_ERROR: 'Internal error occurred',
};
