export const LENTGH_CONSTRAINTS = {
	USERNAME_MIN: 3,
	USERNAME_MAX: 10,
	NAME_MIN: 3,
	NAME_MAX: 25,
	PASSWORD_MIN: 6,
	PASSWORD_MAX: 15,
	TITLE_MIN: 3,
	TITLE_MAX: 100,
	BODY_MIN: 10,
	BODY_MAX: 5000,
	MAX_LIMIT: 100,
	EMAIL_MAX: 255,
	DEFAULT_PAGINATION_LIMIT: 3,
};

export const VALIDATION_MESSAGES = {
	USERNAME_MIN: 'Username should be at least 3 characters long',
	USERNAME_MAX: 'Username must be at most 10 characters',
	USERNAME_INVALID: 'Username can only contain letters, numbers, and underscores',
	NAME_MIN: 'Name should be at least 3 characters long',
	NAME_MAX: 'Name must be at most 25 characters',
	INVALID_EMAIL: 'Invalid email address',
	INVALID_USER_ID: 'Invalid user ID format',
	INVALID_STORY_ID: 'Invalid story ID format',
	TITLE_MIN: 'Title should be at least 3 characters long',
	TITLE_MAX: 'Title must be at most 100 characters',
	BODY_MIN: 'Body should be at least 10 characters long',
	BODY_MAX: 'Body must be at most 5000 characters',
	EMAIL_MAX: 'Email must be at most 255 characters',
	PASSWORD_MIN: 'Password should be at least 6 characters long',
	PASSWORD_MAX: 'Password must be at most 15 characters',
	MAX_LIMIT: 'Limit must be at most 100',
	INVALID_PASSWORD_FORMAT:
		'Password should have at least one uppercase letter, one lowercase letter, one digit, and one special character',
};
